# Copyright 2026 - TODAY, Akretion - Raphael Valyi <raphael.valyi@akretion.com>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/lgpl-3.0.en.html).
# Generated by https://github.com/akretion/sped-extractor and xsdata-odoo
# ruff: noqa: E501
#
# ============================ BOOTSTRAP ONLY ============================
# This file is MACHINE-OWNED and MUST NOT be hand-edited beyond bootstrap.
#
# It currently contains ONLY register 0000 so the module installs and the
# wiring against l10n_br_sped_base can be validated on Odoo 18.0.
#
# The full EFD ICMS/IPI layout 020 (~244 abstract registers) MUST be
# regenerated with akretion/sped-extractor (PR #13, layout 020) and will
# replace this file entirely. Concrete mappings live in sped_efd_icms_ipi.py.
# ========================================================================

import textwrap

from odoo import fields, models


class Registro0000(models.AbstractModel):
    "Abertura do Arquivo Digital e Identificação da entidade"

    _description = textwrap.dedent(f"    {__doc__}")
    _name = "l10n_br_sped.efd_icms_ipi.20.0000"
    _inherit = "l10n_br_sped.declaration"
    _sped_level = 0

    COD_VER = fields.Char(
        string="Código da versão do leiaute conforme",
        xsd_type="numeric_code",
        sped_length="3*",
        help="Código da versão do leiaute conforme a tabela indicada no Ato Cotepe",
    )

    COD_FIN = fields.Char(
        string="Código da finalidade do arquivo",
        xsd_type="numeric_code",
        sped_length="1",
        help=(
            "Código da finalidade do arquivo: 0 - Remessa do arquivo original 1 - "
            "Remessa do arquivo substituto"
        ),
    )

    DT_INI = fields.Date(
        string="Data inicial das informações contidas no arquivo", sped_length="8*"
    )

    DT_FIN = fields.Date(
        string="Data final das informações contidas no arquivo", sped_length="8*"
    )

    NOME = fields.Char(string="Nome empresarial da entidade", sped_length="1")

    CNPJ = fields.Char(
        string="Número de inscrição da entidade no CNPJ",
        xsd_type="numeric_code",
        sped_length="14*",
    )

    CPF = fields.Char(
        string="Número de inscrição da entidade no CPF",
        xsd_type="numeric_code",
        sped_length="11*",
    )

    UF = fields.Char(
        string="Sigla da unidade da federação da entidade", sped_length="2*"
    )

    IE = fields.Char(string="Inscrição Estadual da entidade", sped_length="14")

    COD_MUN = fields.Char(
        string="Código do município do domicílio fiscal",
        xsd_type="numeric_code",
        sped_length="7*",
        help=(
            "Código do município do domicílio fiscal da entidade, conforme a tabela "
            "IBGE"
        ),
    )

    IM = fields.Char(string="Inscrição Municipal da entidade")

    SUFRAMA = fields.Char(string="Inscrição da entidade na Suframa", sped_length="9*")

    IND_PERFIL = fields.Char(
        string="Perfil de apresentação do arquivo fiscal", sped_length="1"
    )

    IND_ATIV = fields.Char(
        string="Indicador de tipo de atividade",
        xsd_type="numeric_code",
        sped_length="1",
        help=(
            "Indicador de tipo de atividade: 0 - Industrial ou equiparado a industrial "
            "1 - Outros"
        ),
    )
